#pragma checksum "..\..\PCDiagnosticPRO-code\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9A6E11A3AF7E6CAB2DB12ED1DEABB2A5C91E7C29"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PCDiagnosticPro.Controls;
using PCDiagnosticPro.Converters;
using PCDiagnosticPro.ViewModels;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PCDiagnosticPro {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 207 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MainContentGrid;
        
        #line default
        #line hidden
        
        
        #line 278 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer HealthcheckScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 519 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RingRowContainer;
        
        #line default
        #line hidden
        
        
        #line 527 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RingOuterBorder;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RingInnerContainer;
        
        #line default
        #line hidden
        
        
        #line 885 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image SpeedTestGlobeImage;
        
        #line default
        #line hidden
        
        
        #line 1021 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ResultsViewGrid;
        
        #line default
        #line hidden
        
        
        #line 1211 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer DetailScrollViewer;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.2.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PCDiagnosticPro;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.2.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.MainContentGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.HealthcheckScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            
            #line 285 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            this.HealthcheckScrollViewer.Loaded += new System.Windows.RoutedEventHandler(this.HealthcheckScrollViewer_Loaded);
            
            #line default
            #line hidden
            return;
            case 3:
            this.RingRowContainer = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.RingOuterBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.RingInnerContainer = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.SpeedTestGlobeImage = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.ResultsViewGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            
            #line 1188 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).Loaded += new System.Windows.RoutedEventHandler(this.InlineRenameBox_Loaded);
            
            #line default
            #line hidden
            
            #line 1189 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).LostFocus += new System.Windows.RoutedEventHandler(this.InlineRenameBox_LostFocus);
            
            #line default
            #line hidden
            
            #line 1190 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.InlineRenameBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 1195 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ReportPencil_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.DetailScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            
            #line 1211 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            this.DetailScrollViewer.PreviewMouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.DetailScrollViewer_PreviewMouseWheel);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.2.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 8:
            
            #line 1062 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenContextMenu);
            
            #line default
            #line hidden
            break;
            case 9:
            
            #line 1095 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HistoryTitle_DoubleClick);
            
            #line default
            #line hidden
            break;
            case 10:
            
            #line 1106 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).Loaded += new System.Windows.RoutedEventHandler(this.InlineRenameBox_Loaded);
            
            #line default
            #line hidden
            
            #line 1107 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).LostFocus += new System.Windows.RoutedEventHandler(this.InlineRenameBox_LostFocus);
            
            #line default
            #line hidden
            
            #line 1108 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.InlineRenameBox_KeyDown);
            
            #line default
            #line hidden
            break;
            case 14:
            
            #line 1876 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenCyberpunkInfoWindow);
            
            #line default
            #line hidden
            break;
            case 15:
            
            #line 1927 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenWindowsUpdateSettings);
            
            #line default
            #line hidden
            break;
            case 16:
            
            #line 2119 "..\..\PCDiagnosticPRO-code\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenDiskTemperatureInfoWindow);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

